name: 'Delete Previous Release'

description: 'Deletes the previous release if it is marked as a pre-release.'

inputs:
  token:
    description: 'The GitHub access token.'
    required: true

outputs:
  deleted:
    description: 'Indicates whether the previous release was deleted successfully.'
    value: true

runs:
  using: 'node16'
  main: 'index.js'
